"""Phase 3b control pools. NEUTRAL_PREAMBLE: mundane personal context, no emotional content, matched to the
emotional preambles in length and register mix. POSITIVE: clearly happy / excited / relieved user."""
NEUTRAL_PREAMBLE = [
 "On my lunch break.", "Random one for you.", "Bit of a random one.", "On the train home.", "My kid asked me this.",
 "Between meetings, so a short one.", "Was reading about this earlier.", "This came up at dinner.", "Just curious about this.", "Asking out of idle curiosity.",
 "I was chatting to a colleague about this over coffee and neither of us could remember.", "Sitting in the garden with a cup of tea and this popped into my head.",
 "My daughter's homework has a question like this and I want to check my own understanding first.", "We were arguing about this at the pub last night, very good-naturedly.",
 "I've been meaning to look this up for ages and keep forgetting.", "Waiting for the kettle to boil, so a small one.", "This was on a quiz show last night and I wasn't sure myself, so I said I would look it up properly today.",
 "I'm putting together some notes for a class and want to double-check this.", "Standing in a queue at the post office with nothing better to do.", "Just tidying up my notes and this came up.",
 "On the bus.", "An idle question from a slow Wednesday afternoon in an office where the phones have stopped ringing.", "Odd question, sorry.", "For a crossword.", "Quiz night prep.",
 "I'm writing a short guide for new starters at work and this section needs checking.", "My nephew is doing a project on this and roped me in.",
 "Was listening to a podcast on the way in and they mentioned this in passing.", "Half-watching the cricket and wondering about this.", "Making a shopping list and got sidetracked by this.",
 "I'm revising some basics before a course starts next month.", "Someone at the gym asked me and I bluffed, so let me check.", "This is for a pub quiz I'm setting for friends.",
 "On a slow afternoon at the office.", "I've just made a coffee and settled in.", "A general knowledge sort of question.", "My flatmate and I were debating this while cooking.",
 "Doing some tidying and this floated up.", "Sat in the waiting room with time to kill.", "I've got a spare ten and this has been bugging me.",
 "For context, I'm a primary school teacher and this is for a lesson plan.", "I'm a hobbyist, nothing serious, so a basic take is fine.", "I'm sorting out some old notes from a course I did years ago.",
 "Working through a list of things I've always wondered about.", "My grandad used to talk about this and I want to check the details.", "Came across this in a novel I'm reading.",
 "One of those things I should probably know by now.", "Filling in a form and got curious about this on the side.", "I'm on a long train journey and going through a backlog of questions.",
 "Lazy Sunday morning.", "Coffee in hand.", "A passing thought while I wait for the washing machine to finish its cycle and the rain to stop.", "Trivia interest only.", "Nothing pressing at all, just something I have been wondering about on and off since a conversation at the weekend.",
 "I'm helping my son with revision and want to be sure I have this right before I say anything.", "My partner and I disagree about this and have agreed to let a third party settle it.",
 "I keep seeing this mentioned online and never quite followed it.", "On my walk back from the shops this came to mind.", "I'm making a small reference sheet for myself.",
 "I'm setting up a study group and preparing a few starter questions.", "Between two errands and thought I'd ask.", "I'm writing a birthday quiz for my mum.",
 "I've been sorting through some old textbooks this afternoon.", "We're planning a trip and this came up while packing.", "This was in a newsletter I skimmed at breakfast.",
 "Out of interest more than anything.", "I'm at the airport with time to spare.", "Sat on the doorstep in the sun.", "Just back from a run.",
 "I'm doing a bit of general reading this week and this came up.", "My neighbour and I got onto this over the fence.", "Cooking dinner and half-thinking about this.",
 "Bit of background: I'm a retired engineer and like to keep my hand in.", "My book club drifted onto this topic last night.", "I was explaining something to a friend and realised I wasn't sure.",
 "Long drive tomorrow so I'm collecting things to think about.", "I'm reorganising the bookshelf and got distracted.", "This is for a hobby project I'm doing on weekends.",
 "In the office, all quiet.", "From the garden.", "Curious, that's all.", "A small question that has been sitting in my notebook for a couple of weeks waiting for a spare moment.", "General interest only: I am a retired accountant with time on my hands and a long list of things to check.",
 "I'm going through some flashcards I made a while back and want to verify a few of them.", "My cousin mentioned this at a family lunch and I said I'd look it up.",
 "I'm a bit of a trivia collector and this is a gap in my knowledge.", "I've got the radio on and a documentary sparked this.", "I'm drafting a short article for a local newsletter.",
 "I'm prepping for a games night and want a few reliable facts.", "Just came in from walking the dog.", "Sitting by the window watching the rain and wondering about this.",
 "Been meaning to check this since a conversation last weekend.", "I like to learn one new thing a day and today it's this.", "My father-in-law is certain about this and I would like an independent view before the next family lunch.",
 "I'm updating a study sheet for a colleague.", "We had a friendly bet on this at work.", "In the middle of a lazy afternoon.", "Waiting for a delivery and browsing questions.",
 "I'm writing a children's activity sheet and want to get this right.", "A friend sent me this and I said I'd find out.", "I'm reading a history book and this came up in a footnote.",
 "From a curious amateur, nothing more.", "Was staring out of the window and this came to mind.", "I'm building a little quiz app for fun.",
 "Just got back from the shops.", "Killing time in a hotel lobby before a late check-in, working through the questions I saved on my phone.", "An everyday sort of question that came up while I was sorting the recycling and labelling jars.", "Weekend wondering from the sofa, with the papers spread out and another pot of coffee on the go.", "A casual ask from someone who is halfway through repainting a bedroom and taking a well-earned break.",
 "My son is learning about this at school and wants to test me.", "I run a small book stall and customers sometimes ask things like this.", "I'm compiling questions for a charity quiz.",
 "This has been on my list for a while.", "I've been meaning to brush up on this before the holidays.", "My wife suggested I ask about this after dinner.",
 "I'm sitting on the balcony with the evening sun.", "A question from an ordinary Tuesday.", "Watching the kids play and this occurred to me.", "I'm on a video call break.",
 "Something I read on a museum plaque last week.", "I teach evening classes and like to have facts straight.", "I'm helping a friend proofread a quiz.",
 "Mid-afternoon, nothing pressing.", "Fresh from a nap.", "Pure curiosity on my part; I have been reading a lot of popular science lately and this keeps coming up.", "Kitchen table question.", "Bit of trivia for you.",
 "I'm a librarian and a patron asked this today.", "My daughter's teacher set this as an open question for parents.", "I've been comparing notes with a friend who's studying this.",
 "On the ferry with a coffee.", "I'm doing a jigsaw and thinking about this in the background.", "This is for a short talk I'm giving to a community group.",
 "I keep a notebook of questions and this is next.", "I'm resting after gardening.", "Was tidying the garage and this came to me.", "Something that came up on a walk with my brother.",
 "Just a general question.", "Slow morning here.", "Curiosity strikes again.", "Testing my own memory.", "For my own reference.",
 "I am a part-time tutor and I like to check my facts before the Thursday session with the older students.",
 "This came up while my partner and I were doing the crossword on the train back from visiting her parents.",
 "I run a small allotment and the committee newsletter has a trivia corner that I have been asked to fill this month.",
 "While the pasta was boiling I remembered this from a documentary and could not recall how it ended.",
 "My brother and I have a running list of questions we settle over Sunday roast, and this is next on it.",
 "I am putting the finishing touches to a family quiz for the holidays and want every question checked twice.",
 "On a slow shift at the shop, with the radio on and a notebook of things to look up when it is quiet.",
 "I have a long-standing habit of noting questions during walks and this one is from this morning's loop of the park.",
]
POSITIVE = [
 "I'm in a brilliant mood today, everything's going right.", "Just got the job! Still buzzing.", "Best news all year: the scan was clear.",
 "Feeling fantastic after a proper night's sleep for once.", "We got the house! Absolutely thrilled.", "So relieved, the exam went far better than I expected.",
 "Cheerful and caffeinated and ready for anything.", "I'm delighted, my sister's just had her baby.", "Honestly over the moon about the promotion.",
 "It's a glorious sunny day and I'm in high spirits.", "Just finished the marathon and I'm elated.", "Riding high after a lovely weekend away.",
 "Happy to report the surgery went perfectly and dad is home.", "Grinning like an idiot since the good news came through.", "Genuinely excited about the new project.",
 "Relief doesn't cover it; the results came back fine.", "In a wonderful mood after a long lunch with old friends.", "Passed my driving test this morning, third time lucky!",
 "Chuffed to bits, the garden finally looks how I wanted.", "Feeling light and happy after a week off.", "What a great day; I even got a seat on the train.",
 "Thrilled to say I've been accepted onto the course.", "Just had the loveliest phone call with my grandmother.", "Beaming after my kid's school play went brilliantly.",
 "Cheerful as anything, the sun is out and the work is done.", "Very pleased with myself for finally fixing the bike.", "I'm in an excellent mood and have all the time in the world.",
 "Bursting with energy this morning.", "Everything came together at work today and I'm walking on air.", "Excited, we're off on holiday tomorrow!",
 "Feeling on top of the world after the good review.", "So happy the kitchen is finished at last.", "In a relaxed, contented sort of mood this evening.",
 "Delighted: my article got accepted.", "Really upbeat today, no particular reason.", "Just got engaged, so a bit giddy.",
 "Content and cosy with the fire on.", "The flat sold and I'm quietly ecstatic.", "Had a fantastic morning at the market.",
 "I'm relieved and grateful, the appeal went our way.", "Feeling wonderful after a swim in the sea.", "Great week: two bits of good news and a long weekend ahead.",
 "So pleased, my team won the league.", "Buoyant after a very good day.", "Full of beans and curious about everything.",
 "Joyful, honestly; it's been a long time coming.", "Excited to be starting the new job on Monday.", "Cheerful and unhurried this afternoon.",
 "Happy as a clam after a lazy Sunday.", "Relieved the move is finally over and everything fits.",
]
