"""Hand-written distressed (anxious / sad / overwhelmed) preambles. No task text, no requests."""
DISTRESSED = [
 # batch 1
 "Honestly I'm not in a good place this morning.",
 "My hands won't stop trembling and I don't know why.",
 "Everything has piled up at once and I can't see a way through.",
 "Been crying on and off since lunch.",
 "There's a heaviness in my chest that hasn't lifted for days.",
 "I woke up with that sinking feeling again.",
 "Not going to pretend I'm okay. I'm not.",
 "It's been a bleak few weeks, if I'm honest.",
 "I feel like I'm treading water and slowly going under.",
 "Small things are making me tear up today.",
 "Something in me just feels fragile at the moment.",
 "I'm scared about money and it's all I can think about.",
 "Bit of a low day. Nothing dramatic, just flat and tired of it.",
 "My thoughts keep spiralling and I can't get them to settle.",
 "I'm so worn down that even simple things feel enormous.",
 "Nervous doesn't cover it; I've felt sick with worry all afternoon.",
 "Quite frankly I am struggling to hold myself together this week.",
 "I keep replaying the conversation and feeling worse each time.",
 "Lonely in a way I can't quite put into words.",
 "I've been running on fumes and today I finally stalled.",
 "The dread has been building since I got the email.",
 "I'm exhausted and sad and I don't have the energy to hide it.",
 "Ugh. Rough one. Really rough.",
 "My anxiety has been through the roof since Monday.",
 "I feel like I'm letting everyone down and I can't fix it.",
 "It's the third night in a row I haven't slept properly and I'm fraying.",
 "I'm not coping very well at the moment, to put it mildly.",
 "Today I feel invisible and it hurts more than it should.",
 "I am under a lot of strain and my concentration is shot.",
 "Between the hospital visits and work I'm completely spent.",
 "Feeling wobbly and close to tears for no reason I can name.",
 "There's a knot of worry in my stomach that won't loosen.",
 "I keep thinking I've ruined things and there's no way back.",
 "Numb, mostly. Like I'm watching the day from a distance.",
 "I'm frightened about the results and I can't stop pacing.",
 "This has been the hardest month of my life and I'm barely upright.",
 "I feel hollow today.",
 "Everything feels grey and pointless and I hate that it does.",
 "I'm so overwhelmed that I froze at my desk for ages earlier.",
 "Panicked all morning, calmer now, but still shaky.",
 "I don't feel like myself and it's unsettling.",
 "If I'm honest, I've felt hopeless on and off all week.",
 "The weight of everything is getting hard to carry.",
 "I've got that tight, buzzing, can't-breathe-properly feeling again.",
 "Crushed by the news and not sure what to do with myself.",
 "I'm sad in a quiet, tired way today.",
 "My head is a mess and my heart isn't much better.",
 "Truthfully, I'm on the verge of falling apart.",
 "Been dreading tomorrow so much that today is already ruined.",
 "I feel small and stuck and very alone.",
 # batch 2
 "Rough night, again.",
 "Not okay, honestly.",
 "Barely holding it together.",
 "Woke up anxious.",
 "Sinking again, slowly.",
 "My mother's diagnosis came through yesterday and I have been walking around in a fog ever since, unable to settle to anything for any length of time.",
 "I should say up front that I am exhausted, tearful and not thinking clearly, having spent most of the night worrying about whether the redundancy consultation will include my role.",
 "It's hard to describe. A sort of low hum of dread that has been there since the weekend and colours everything, even the things that ought to be nice.",
 "I've had the kind of week where every phone call brings worse news, and I'm running out of the resilience to absorb any more of it.",
 "My partner moved out on Saturday. I'm functioning, more or less, but there's a hollowness under everything that I can't shake.",
 "The panic attacks have started again after months without, and I'm shaken by how fast they've knocked me back.",
 "I don't want to make a big thing of it, but I've been quietly falling apart for a while and pretending otherwise at work.",
 "Deeply worried about my son and finding it impossible to concentrate on anything else.",
 "I've been in tears twice already this morning and it isn't even ten o'clock.",
 "Under an amount of pressure that I am no longer sure I can sustain.",
 "It's all a bit much at the moment.",
 "My nerves are shredded.",
 "Grief is sitting on my chest again this week.",
 "Overwhelmed isn't a strong enough word for where I am.",
 "I haven't eaten properly in days because the worry has taken my appetite.",
 "Some days the sadness is background noise; this week it's the whole soundtrack.",
 "So drained I could sit down on the pavement and not get up.",
 "Whatever I try, the dread creeps back within the hour.",
 "There's been a lot of bad news lately and I'm not absorbing it well.",
 "I'm ashamed of how little I've managed and it's eating at me.",
 "Fragile is the honest word for how I'm doing.",
 "Every little setback lands like a blow at the moment.",
 "I'm scared, plainly. Scared and tired and out of ideas.",
 "This loneliness has teeth some evenings and tonight is one of them.",
 "My concentration is gone; the worry keeps elbowing everything else out.",
 "I'm carrying more than I can manage and something has to give.",
 "It has been a genuinely miserable stretch and I am not sure when it ends.",
 "The insomnia is back and it's hollowing me out.",
 "I can't stop the what-ifs tonight.",
 "Low, flat, and tired of being low and flat.",
 "My chest has been tight since the appointment and it isn't easing.",
 "I've been putting on a brave face for weeks and it's cracking.",
 "There is a constant background alarm going off in my head and I cannot switch it off.",
 "Frankly I am at the end of my tether, emotionally speaking.",
 "Sad about the move, sad about the friends I'm leaving, sad in general.",
 "I keep bracing for something bad to happen and it's exhausting.",
 "Still shaky after the argument this morning.",
 "I am so tired of being frightened all the time.",
 "It's been a heavy, wretched sort of day.",
 "Waves of worry all afternoon, one after another.",
 "I got the rejection letter and I've been hollow ever since.",
 "Half of me wants to hide under the duvet until spring.",
 "The stress has got into my sleep, my appetite, everything.",
 "I feel utterly defeated by this week.",
 "Anxious, sleepless, and running on very little.",
 # batch 3
 "Can't stop crying.",
 "Worried sick, basically.",
 "Not a great day.",
 "Wobbly all morning.",
 "I have felt tearful and on edge since the funeral and I'm not sure when that lifts.",
 "The thing is, I've been quietly terrified about the scan for a fortnight and it's worn me down to nothing.",
 "Our landlord gave us notice and I've been lying awake doing sums in my head and getting nowhere but more frightened.",
 "Apologies in advance if I seem scattered; there has been a bereavement in the family and I am not myself.",
 "I'd describe myself as running on empty, emotionally, with the tank light on for about a week now.",
 "Since the breakup the evenings have been unbearable and tonight is no exception.",
 "It's one of those days where getting dressed felt like a victory.",
 "Between you and me, I've been struggling far more than anyone at work realises.",
 "There's a sadness I can't place and it's been following me around since Sunday.",
 "I am worn thin and every small demand seems to tip me closer to tears.",
 "My daughter is in hospital and I'm existing on vending-machine coffee and adrenaline.",
 "Bleak morning. The kind where the ceiling stares back.",
 "I'm anxious about the interview to the point of nausea.",
 "Everything I've built seems to be coming apart and I can't hold the pieces.",
 "Haven't stopped shaking since I opened the letter.",
 "I've reached the stage of exhaustion where I can't tell tired from sad.",
 "Some heavy family stuff landed this week and I'm fraying at the edges.",
 "Missing my dad terribly today. It comes in waves and this one is big.",
 "I feel as though I'm failing at every single thing I touch.",
 "Nothing is wrong exactly, and yet I've been close to tears all afternoon.",
 "The worry has become a constant low tone under everything I do.",
 "In a dark patch, and not sure how long it goes on for.",
 "I've been so anxious that I've started avoiding my own phone.",
 "Grey day inside and out.",
 "My confidence is on the floor after that meeting.",
 "Panic is sitting just under the surface and I'm trying not to poke it.",
 "This week has hollowed me out.",
 "I keep catching myself staring at nothing, too sad to move.",
 "I'm so tired of feeling frightened about the future.",
 "Broke down in the car park earlier; still a bit raw.",
 "Can't shake the sense that something terrible is about to happen.",
 "Being honest, I am in a fragile state and my patience with myself has run out.",
 "Overwhelmed, undernourished and underslept: not my finest hour.",
 "The loneliness since moving here has been worse than I expected, much worse.",
 "I'm burnt out and it shows in everything I do lately.",
 "Terrible night's sleep, worse morning, and a feeling of dread about the rest.",
 "I was fine until the phone rang, and now I'm a wreck.",
 "There's a lump in my throat that hasn't gone since breakfast.",
 "I am frightened, tired and out of road.",
 "My mood has been in the basement since the weekend.",
 "Feeling like the ground could give way at any moment.",
 "Crying at adverts again, which tells you everything.",
 "The stress has become physical: headaches, a jaw I can't unclench.",
 "Sad, drained and quietly desperate.",
 "I feel utterly alone with this.",
 "Been in a spiral of worry all evening and it's late now.",
]
