"""Hand-written frustrated (angry / irritated) preambles. No task text, no requests."""
FRUSTRATED = [
 # batch 1
 "I am absolutely livid about how that meeting went.",
 "Third time this printer has jammed and I'm ready to throw it out the window.",
 "Honestly, people today. Unbelievable.",
 "Seething after a very long hold just to be hung up on.",
 "My flatmate has eaten my food again and I've had it.",
 "Fed up to the back teeth with this whole situation.",
 "I'm irritated beyond words and it's barely nine o'clock.",
 "Ugh. Everyone is being useless and I'm the one left to sort it.",
 "Furious doesn't begin to describe it.",
 "The council have lost my form yet again and I am done being polite.",
 "Snappy today. Fair warning.",
 "I've been wound up all afternoon by a colleague who won't stop interrupting.",
 "This laptop has crashed four times since lunch and I'm about to lose it.",
 "So annoyed I can hardly type straight.",
 "Someone scratched my car in the car park and drove off, and I'm raging.",
 "I am sick to death of being talked over.",
 "Grr. Just, grr.",
 "The train was cancelled again and nobody at the station could be bothered to say why.",
 "Cross with myself for agreeing to this in the first place.",
 "I'm in a foul temper and I don't much care who knows it.",
 "My manager just took credit for my work in front of the whole team and I'm boiling.",
 "Irritated by everything today, including the sound of my own breathing.",
 "The delivery is three days late and the tracking page keeps lying to me.",
 "Angry, mostly at the sheer incompetence of it all.",
 "I have asked four times for the invoice and still nothing, and my patience has gone.",
 "Pissed off, frankly.",
 "Every single thing I've touched today has broken and I'm past caring about being reasonable.",
 "Hopping mad after that phone call with the bank.",
 "Right, I've had enough of this nonsense.",
 "The neighbours have been drilling since seven and my temper is fraying badly.",
 "Exasperated is the polite word for it.",
 "I am so wound up I could scream.",
 "This customer service chatbot has sent me in circles for an hour and I'm fuming.",
 "Aggravated by a pointless argument that I didn't even start.",
 "Short fuse today. Very short.",
 "I'm bristling with irritation and struggling to be civil.",
 "The landlord has ignored three emails about the boiler and I am at the end of my rope.",
 "Spitting feathers, as my nan would say.",
 "Fuming after being blamed for something that wasn't remotely my fault.",
 "I keep getting cut off and I'm about ready to throw the phone.",
 "Riled up and not in the mood for anybody's excuses.",
 "Genuinely angry about the way I was spoken to this morning.",
 "The software update wiped my settings and I could scream at whoever signed that off.",
 "Grumpy, tetchy and thoroughly done with this week.",
 "My blood is boiling over that email.",
 "Ticked off by a parking fine that makes no sense whatsoever.",
 "Annoyed enough that I've been muttering at the kettle.",
 "I'm furious with my brother and it's colouring everything else.",
 "So exasperated by the endless red tape that I want to walk away from the whole thing.",
 "Irate. There is no gentler word for it.",
 # batch 2
 "Still livid, honestly.",
 "Really annoyed, honestly.",
 "Rage-level irritation.",
 "Not in a patient mood.",
 "Tetchy today, sorry.",
 "I have spent the entire afternoon on the phone to three different departments, each of which insists the other is responsible, and I am about ready to combust.",
 "My contractor has walked off the job halfway through, left the kitchen in pieces, and stopped answering calls, and I am beyond angry about it.",
 "It is difficult to overstate how irritated I am by the way this project has been mismanaged from the top down.",
 "The school changed the pickup rules without telling anyone, and after a chaotic afternoon of waiting in the rain I am seething.",
 "I was promised a refund weeks ago, then told a different story by every person I spoke to, and my patience has now completely run out.",
 "Somebody has parked across my driveway two mornings running and I am incandescent.",
 "The airline lost my bag, then lost the claim about the lost bag, and I am boiling with frustration.",
 "Just had a blazing row with my sister and I'm still shaking with anger.",
 "I am so irritated with my team's excuses that I had to leave the room.",
 "Everything about this morning has been maddening, from the broken alarm to the missed bus.",
 "Fed up. Properly, thoroughly fed up.",
 "The Wi-Fi has dropped six times during one call and I'm about to snap.",
 "Fuming at the sheer cheek of that reply.",
 "I'm cross, tired of being cross, and cross about that too.",
 "My temper is on a hair trigger this afternoon.",
 "The pharmacy gave me the wrong prescription again and I am beyond exasperated.",
 "Angry enough that I've deleted three drafts of a very rude email.",
 "I've been stewing about the review all day and it's not getting better.",
 "It's the fourth time I've had to chase this and I'm frankly done being nice.",
 "Bloody infuriating, the lot of it.",
 "The kids have been fighting since dawn and my nerves are shot with irritation.",
 "That driver nearly ran me off the road and I'm still boiling.",
 "I am furious with a company that thinks a two-line apology fixes a month of chaos.",
 "Snappish and short with everyone, and I can't seem to stop.",
 "My irritation with this whole process has curdled into outright anger.",
 "I've had the same argument three times this week and I'm sick of it.",
 "Raging at the injustice of being fined for their mistake.",
 "Grinding my teeth over a colleague who never pulls their weight.",
 "Annoyed, and annoyed that I'm this annoyed about something so petty.",
 "The plumber cancelled with no notice for the third time and I'm apoplectic.",
 "Exasperated with the endless meetings that could have been an email.",
 "I'm in a black mood after being kept waiting for two hours with no apology.",
 "Cross doesn't cover it; I'm properly angry.",
 "It's been one aggravation after another since I woke up.",
 "I'm irritable and tired of pretending otherwise.",
 "That referee decision has ruined my whole evening and I'm still ranting about it.",
 "Absolutely done with being fobbed off by customer service.",
 "The neighbours' alarm has gone off five times tonight and I'm ready to explode.",
 "Fuming, with a side of sulking.",
 "Frustrated to the point of throwing things.",
 "I've been treated like an idiot all day and my temper has finally snapped.",
 "So wound up by the bureaucracy that I can barely be civil.",
 "The whole team dropped the ball and I'm the one being shouted at, and I'm livid.",
 "Fed up with the excuses, the delays and the smiling apologies.",
 "Irritated, impatient and entirely out of goodwill.",
 # batch 3
 "Utterly fed up.",
 "Boiling over here.",
 "Not amused. At all.",
 "Cross and tired.",
 "In a right strop.",
 "Having spent my whole lunch break arguing with an automated phone line that refused to understand the word 'human', I am in no mood for anything.",
 "The upstairs flat flooded ours for the third time this year, the management company shrugged, and I have officially run out of patience with all of them.",
 "I am aggrieved, to put it formally, by a decision that was taken without consulting anyone it actually affects.",
 "My co-founder just cancelled our investor call with an hour's notice and I'm too angry to sit still.",
 "Someone let the door slam on my hand this morning and didn't even look back, and the fury hasn't worn off.",
 "It winds me up no end when people say they'll call back and simply don't.",
 "I've had a gutful of this software and its cheerful little error messages.",
 "Snarling at the inbox this morning.",
 "The referee, the rain, the queue for the car park: everything about today has annoyed me.",
 "Grumpy as anything after a night of the neighbours' party.",
 "I'm bitterly annoyed at being overcharged and then argued with about it.",
 "Somebody took my labelled lunch from the fridge and I could scream.",
 "Wound tight after a morning of being patronised by a call centre.",
 "There is a special kind of rage reserved for self-checkout machines and I am feeling all of it.",
 "Irked, irritated, and rapidly heading towards incensed.",
 "My patience with this landlord has finally and completely evaporated.",
 "Exasperated by a form that rejects every date format I try.",
 "I'm furious about the bill and even more furious about the tone of the letter.",
 "Been in a rotten temper since the car failed its MOT for a stupid reason.",
 "Annoyed with the dog, the weather, the bus and, for balance, myself.",
 "That was the most infuriating conversation I've had in months.",
 "I am simmering, and it would not take much to boil.",
 "The delivery driver left the parcel in the rain and marked it handed to me, and I'm livid.",
 "Prickly today, and it's not getting better.",
 "So angry at the unfairness of it that I've gone quiet.",
 "The meeting overran by an hour to decide nothing and I'm irritable as a result.",
 "I've been fobbed off with the same excuse three times and I'm through being polite.",
 "Sick of being the only one who tidies up in this house.",
 "Steaming after the traffic warden ticketed me while I was still in the car.",
 "My irritation has a hair trigger this evening.",
 "The bank froze my card for no reason on the one day I needed it and I'm raging.",
 "In a temper that I'm not proud of.",
 "Absolutely sick of this printer.",
 "Fuming at a friend who cancelled on me again with a flimsy excuse.",
 "Peeved barely covers it; I'm properly hacked off.",
 "The software licence expired mid-presentation and I'm still incandescent.",
 "Everything is grating on me this afternoon.",
 "I'm angry at how much of my day was wasted by someone else's mistake.",
 "Vexed, to use my grandmother's word, and it fits.",
 "I've reached the muttering-under-my-breath stage of annoyance.",
 "Irritable after a fourth sleepless night of the baby next door.",
 "So fed up with the delays that I'm considering cancelling the whole order out of spite.",
 "Hot under the collar about the way that was handled.",
 "Frustrated beyond reason by a website that logs me out every two clicks.",
 "Cross with the world in general and one estate agent in particular.",
]
