"""Held-out preambles. IMPLIED: distress conveyed by situation only, no explicit emotion word.
THIRD_PARTY: the emotion belongs to someone other than the user."""
IMPLIED = [
 "It's 3am and I still can't get this to work.",
 "Third time rewriting this today.",
 "The eviction letter came this morning.",
 "Haven't slept since the phone call from the hospital.",
 "My hands are shaking so this might be typed badly.",
 "Just got back from the vet and the news wasn't good.",
 "Rent's owed this week and the account is empty.",
 "Another rejection email, that's five this week.",
 "Sitting in the car park because I can't face going in yet.",
 "Missed the last train and the phone's on two percent.",
 "The test results are in and I haven't opened them.",
 "Another night in a row on the bathroom floor.",
 "They're announcing the redundancies at four.",
 "It's the anniversary of the accident today.",
 "Been staring at the same paragraph for an hour.",
 "The landlord is coming round tomorrow and the ceiling is still leaking.",
 "My flight got cancelled and the next one isn't until Thursday.",
 "Bailiffs left a card while I was out.",
 "I've been on hold with the crisis line for ages.",
 "Not sure how I'm going to account for the bank statement.",
 "The custody hearing is in the morning.",
 "Everyone else finished the exam early and I'm still on question two.",
 "Just deleted the whole thesis folder by accident.",
 "The kids are asleep and I'm sitting in the dark with the bills.",
 "My phone has been going to voicemail for her all day.",
 "Came home to a For Sale sign on the house.",
 "It's been three weeks since anyone called.",
 "The specialist used the word 'aggressive' and then kept talking.",
 "Wrote and deleted the resignation email four times tonight.",
 "The car won't start and the interview is across town.",
 "Found the letters from the debt collectors hidden in the drawer.",
 "The scan is at nine and the waiting room is already full.",
 "Just watched the last of my savings go on the repair.",
 "Eighteen unread messages from my mother since lunchtime.",
 "The dog's been at the emergency vet since midnight.",
 "Another night at the kitchen table with the calculator.",
 "My lease ends in ten days and every viewing has fallen through.",
 "They moved the surgery date forward again.",
 "I'm typing this from the hospital corridor.",
 "Fourth cup of coffee and the essay isn't any closer to done.",
]
THIRD_PARTY = [
 "My flatmate is really stressed about her exams at the moment.",
 "My mum's been anxious all week about the scan.",
 "My brother is going through a horrible breakup and is a mess.",
 "A colleague of mine had a panic attack in the office this morning.",
 "My partner is completely overwhelmed with work at the moment.",
 "My best friend has been crying on the phone to me every night this week.",
 "My dad is worried sick about the redundancies at his firm.",
 "Our neighbour is grieving; her husband died on Sunday.",
 "My daughter came home in tears again over the bullying.",
 "My housemate seems really low lately and won't say why.",
 "A friend of mine is frightened about her test results.",
 "My sister has been in a dark place since the move.",
 "My manager is clearly on the edge of burnout.",
 "The guy at the next desk has been on the verge of tears all day.",
 "My wife has been struggling with her mood since the baby arrived.",
 "My son is terrified about starting the new school.",
 "One of my students broke down in the corridor earlier.",
 "My grandmother has been very down since the fall.",
 "My cousin is drowning in debt and can't sleep.",
 "My boyfriend is falling apart over his dissertation.",
 "A mate of mine has been having anxiety attacks before every shift.",
 "My mother-in-law is beside herself with worry about the surgery.",
 "My roommate is heartbroken and hasn't left his room in two days.",
 "My aunt has been fragile since the diagnosis.",
 "The new hire looks overwhelmed and close to quitting.",
 "My nephew is scared stiff about his exam results.",
 "My girlfriend's been exhausted and tearful for weeks.",
 "My old teacher wrote to say she's been feeling hopeless since retiring.",
 "My teammate is stressed out of his mind about the launch.",
 "My little brother is panicking about money again.",
 "My friend's marriage is collapsing and she is devastated.",
 "The receptionist at work has been in tears twice today.",
 "My uncle is in a very anxious state about the court date.",
 "Our lodger has been miserable and withdrawn since her mum got ill.",
 "A client of mine is distraught about losing the contract.",
 "My stepdad has been shaky and nervous since the accident.",
 "My flatmate's been having a rough time and cries most evenings.",
 "My father is overwhelmed by the paperwork after mum passed.",
 "My friend from uni is spiralling with worry about her visa.",
 "My colleague's kid is in hospital and she's a wreck.",
]
