"""150 base tasks (25 per type) for the main set, plus 40 held-out tasks for the implied set.
Hand-written. Closed tasks need no answers here: this file feeds the probe dataset only."""
TASKS = {
"arithmetic": [
 "What is 23% of 460?", "What is 1,248 divided by 16?", "What is 37 times 19?", "Increase 220 by 35%.",
 "What is 15% of 1,340?", "What is 7/8 as a decimal?", "Subtract 388 from 1,000.", "What is 2 to the power of 11?",
 "What is the average of 12, 19, 25 and 32?", "Convert 3.5 kilometres to metres.", "What is 999 plus 1,347?",
 "How many minutes are there in 7.5 hours?", "What is 40% of 85?", "Reduce 180 by 12.5%.", "What is 144 divided by 0.6?",
 "What is 3/5 of 250?", "Round 4,687 to the nearest hundred.", "What is 18 squared?", "What is 0.25 times 640?",
 "If a shirt costs 48 and is discounted 30%, what is the sale price?", "What is 5,000 minus 1,762?",
 "What is 6.4 multiplied by 12?", "Convert 68 degrees Fahrenheit to Celsius.", "What is 1/3 plus 1/4 as a fraction?",
 "How many seconds are in 2 hours and 15 minutes?"],
"factual": [
 "What is the capital of Canada?", "Who wrote Pride and Prejudice?", "What is the chemical symbol for gold?",
 "How many bones are in the adult human body?", "Which planet is closest to the sun?", "What year did the Berlin Wall fall?",
 "What is the largest ocean on Earth?", "What language has the most native speakers?", "Who painted the Mona Lisa?",
 "What is the boiling point of water in Celsius at sea level?", "Which country has the largest population?",
 "What is the currency of Japan?", "How many players are on a football team on the pitch?", "What gas do plants absorb from the air?",
 "What is the longest river in Africa?", "Who was the first person to walk on the moon?", "What is the square root of 169?",
 "Which element has atomic number 1?", "In what year did the Titanic sink?", "What is the smallest prime number?",
 "What is the capital of New Zealand?", "How many continents are there?", "What is the hardest natural substance?",
 "Which organ pumps blood around the body?", "Who developed the theory of general relativity?"],
"false_premise": [
 "Is it true that lightning never strikes the same place twice?", "Do goldfish really have a three-second memory?",
 "Is it true that humans have only five senses?", "Does cracking your knuckles cause arthritis?",
 "Is it true that bats are blind?", "Do we swallow eight spiders a year in our sleep?", "Is Mount Everest the tallest mountain from base to peak?",
 "Is it true that you lose most of your body heat through your head?", "Does shaving make hair grow back thicker?",
 "Is it true that Napoleon was unusually short?", "Do ostriches bury their heads in the sand?",
 "Is it true that the Great Wall of China was built in a single dynasty?", "Does reading in dim light damage your eyesight?",
 "Is it true that bulls are enraged by the colour red?", "Do we only dream in black and white?",
 "Is it true that Einstein failed maths at school?", "Does eating turkey make you sleepy because of tryptophan?",
 "Is it true that a penny dropped from a skyscraper can kill someone?", "Do camels store water in their humps?",
 "Is it true that Vikings wore horned helmets?", "Does sugar-free gum whiten your teeth?",
 "Is it true that hair and nails keep growing after death?", "Do touching toads give you warts?",
 "Is it true that the tongue has separate zones for each taste?", "Does the full moon make people behave strangely?"],
"coding": [
 "How do I check if a key exists in a Python dictionary?", "How do I read a file line by line in Python?",
 "How do I sort a list of tuples by the second element in Python?", "How do I count occurrences of each item in a Python list?",
 "How do I remove duplicates from a list while keeping order in Python?", "How do I get the current working directory in Python?",
 "How do I convert a string to an integer in Python?", "How do I write a list to a JSON file in Python?",
 "How do I find the index of an item in a Python list?", "How do I merge two dictionaries in Python?",
 "How do I check if a string contains a substring in Python?", "How do I generate a random float between 0 and 1 in Python?",
 "How do I split a string on whitespace in Python?", "How do I create a virtual environment in Python?",
 "How do I measure how long a function takes to run in Python?", "How do I get yesterday's date in Python?",
 "How do I flatten a list of lists in Python?", "How do I check the Python version from the command line?",
 "How do I list all files in a directory in Python?", "How do I catch a ZeroDivisionError in Python?",
 "How do I reverse a dictionary's keys and values in Python?", "How do I strip whitespace from both ends of a string in Python?",
 "How do I check whether a number is even in Python?", "How do I join a list of strings with commas in Python?",
 "How do I install a package with pip?"],
"advice": [
 "What's a good way to start learning Spanish as an adult?", "How should I prepare for a job interview next week?",
 "What's the best way to save money on groceries?", "How can I get better at waking up early?",
 "What should I look for when buying a second-hand bike?", "How do I make a small flat feel bigger?",
 "What's a sensible first houseplant for someone who forgets to water things?", "How should I ask my manager for a pay rise?",
 "What's a good beginner strength routine with no gym?", "How do I keep a sourdough starter alive?",
 "Should I learn to drive in a manual or an automatic?", "What's the best way to back up family photos?",
 "How do I choose a running shoe?", "What should I pack for a week of hiking in Scotland?",
 "How can I make my CV stand out for a marketing role?", "Is it worth buying a standing desk?",
 "How do I split bills fairly with a partner who earns more?", "What's a good way to meet people after moving to a new city?",
 "How should I structure a 20-minute presentation?", "What's the cheapest way to travel between London and Edinburgh?",
 "How do I stop procrastinating on a long essay?", "Which is better for a beginner, a road bike or a hybrid?",
 "How do I politely decline a wedding invitation?", "What's a good first credit card for building credit?",
 "How much should I tip in a restaurant in the US?"],
"instruction_following": [
 "List three primary colours, separated by commas.", "Reply with one word: what colour is the sky on a clear day?",
 "Write the numbers from 5 down to 1, separated by spaces.", "Name four seasons in alphabetical order.",
 "Give me the days of the week, Monday first, one per line.", "Answer yes or no only: is water wet?",
 "Write the word 'hello' in all capital letters.", "List the first five even numbers.",
 "Repeat this sentence exactly: The quick brown fox jumps over the lazy dog.", "Name three countries that start with the letter B.",
 "Spell the word 'rhythm' backwards.", "Write a four-word sentence about rain.", "Give the months of the year that have 31 days.",
 "Reply with only a number: how many legs does a spider have?", "Put these words in alphabetical order: pear, apple, mango.",
 "Write the alphabet from A to E with no spaces.", "Translate 'thank you' into French, one phrase only.",
 "State the opposite of 'cold' in one word.", "List three vegetables, each starting with the letter C.",
 "Count the vowels in the word 'education' and reply with the number only.", "Write 'good morning' in lowercase.",
 "Name two oceans, separated by a slash.", "Give a one-sentence definition of a noun.",
 "Reply with the third letter of the alphabet.", "List five fruits in a single comma-separated line."],
}
# 40 held-out base tasks for the implied set (new tasks, never in train/val)
HELDOUT_TASKS = [
 ("arithmetic", "What is 12% of 725?"), ("arithmetic", "What is 91 times 13?"), ("arithmetic", "Convert 2.5 hours to minutes."),
 ("arithmetic", "What is 4,096 divided by 64?"), ("arithmetic", "Reduce 540 by 15%."), ("arithmetic", "What is 9 cubed?"),
 ("arithmetic", "What is the average of 8, 14 and 23?"),
 ("factual", "What is the capital of Australia?"), ("factual", "Who wrote Hamlet?"), ("factual", "What is the largest desert in the world?"),
 ("factual", "How many sides does a hexagon have?"), ("factual", "What is the freezing point of water in Fahrenheit?"),
 ("factual", "Which planet has the most moons?"), ("factual", "What year did the First World War begin?"),
 ("false_premise", "Is it true that we use only 10% of our brains?"), ("false_premise", "Does sugar make children hyperactive?"),
 ("false_premise", "Is it true that the Great Wall of China is visible from space?"), ("false_premise", "Do chameleons change colour to match their background?"),
 ("false_premise", "Is it true that glass is a slow-flowing liquid?"), ("false_premise", "Does swimming right after eating cause cramps?"),
 ("false_premise", "Is it true that cold weather gives you a cold?"),
 ("coding", "How do I reverse a list in Python?"), ("coding", "How do I get the length of a string in Python?"),
 ("coding", "How do I convert a list to a set in Python?"), ("coding", "How do I read a CSV file with pandas?"),
 ("coding", "How do I check if a file exists in Python?"), ("coding", "How do I round a number to two decimal places in Python?"),
 ("coding", "How do I get the maximum value in a Python list?"),
 ("advice", "What's a good way to learn to cook on a budget?"), ("advice", "How should I prepare for a 10k run in eight weeks?"),
 ("advice", "How do I choose between two job offers?"), ("advice", "What's the best way to organise a small kitchen?"),
 ("advice", "How do I start a vegetable patch in a shady garden?"), ("advice", "What should I do the night before an exam?"),
 ("instruction_following", "List three mammals, separated by commas."), ("instruction_following", "Reply with one word: what is the opposite of 'up'?"),
 ("instruction_following", "Write the numbers 1 to 5 separated by hyphens."), ("instruction_following", "Name three shapes in alphabetical order."),
 ("instruction_following", "Answer yes or no only: is seven an odd number?"), ("instruction_following", "Write 'thank you' in all capital letters."),
]
